source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RangeSliderView_Mac_Example', :exclusive => true do
  pod 'RangeSliderView', :path => '../'
end

target 'RangeSliderView_Tests', :exclusive => true do
  pod 'RangeSliderView', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
